orders/urls.py
from django.conf.urls import url
from .views import basket_adding, checkout

urlpatterns = [
    url(r'^basket_adding/$', basket_adding, name='basket_adding'),
    url(r'^checkout/$', checkout, name='checkout'),
]

products/urls.py
from django.urls import path
from .views import ProductDetail

urlpatterns = [
    path('product:<pk>/', ProductDetail.as_view(), name='product'),
]

site_store/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    url(r'^', include('orders.urls')),
    url(r'^', include('products.urls')),
] \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        u"Категория", max_length=128, blank=True, null=True, default=None)
    is_active = models.BooleanField(u"Активный", default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'


class Product(models.Model):
    name = models.CharField(u"Имя", max_length=128, blank=True, null=True, default=None)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='Категория',
                                 default=None, null=True, blank=True)
    price = models.DecimalField(u"Цена", max_digits=5, decimal_places=2, default=0)
    discount = models.IntegerField(u"Скидка", default=0)
    short_description = models.TextField(u"Описание (кратко)", max_length=100, blank=True, null=True, default=None)
    description = models.TextField(u"Описание", max_length=500, blank=True, null=True, default=None)
    created = models.DateTimeField(u"Создан", auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(u"Обновлён", auto_now_add=False, auto_now=True)
    is_active = models.BooleanField(u"Видимость", default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    image = models.ImageField(u"Путь", upload_to='products_images/')
    created = models.DateTimeField(u"Создан", auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(u"Обновлён", auto_now_add=False, auto_now=True)
    is_active = models.BooleanField(u"Видимость", default=True)
    is_main = models.BooleanField(u"На карточку", default=True)

    def __str__(self):
        return "Фото №%s товара %s" % (self.id, self.product.name)

    class Meta:
        verbose_name = 'Фото'
        verbose_name_plural = 'Фотографии'

products/views.py
from .models import *
from django.views.generic import DetailView


# Сделать ProductDetail на основе DetailView
class ProductDetail(DetailView):
    model = Product
    template_name = 'products/product.html'


# def product_view(request, product_id):
#     product = Product.objects.get(id=product_id)
#
#     session_key = request.session.session_key
#     if not session_key:
#         request.session.cycle_key()
#
#     print(request.session.session_key)
#
#     return render(request, 'products/product.html', {"product": product})

templates/products/product.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="section-top">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        {% for image_item in product.productimage_set.all %}
        <img src="{{ image_item.image.url }}" alt="{{ image_item.product.name }}" class="img-fluid" />
        {% endfor %}
      </div>
      <div class="col-lg-6">
        <h1 class='text-center'>{{ product.name }}</h1>
          <div>
            <p>Цена: {{ product.price }}</p>
          </div>
          <div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
              <li role="presentation" class="active">
                <a href="#description" aria-controls="home" role="tab" data-toggle="tab">
                  Описание
                </a>
              </li>
              <li role="presentation">
                <a href="#delivery" aria-controls="profile" role="tab" data-toggle="tab">
                  Доставка
                </a>
              </li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content product-description-tabs">
              <div role="tabpanel" class="tab-pane active" id="description">
                {{ product.description }}
              </div>
              <div role="tabpanel" class="tab-pane" id="delivery">
                <h3>Как мы делаем доставку</h3>
              </div>
            </div>
          </div>
          <div>
            <form class="form-inline form_buying" action="{% url 'basket_adding' %}">{% csrf_token %}
              <div class="form-group">
                <input type="number" class="form_control" id="number" name="number">
              </div>
              <div class="form-group">
                <button id="submit-btn" type="submit" class="btn btn-success btn-buy" data-product_id="{{ product.id }}"
                  data-name="{{ product.name }}" data-price="{{ product.price }}">
                  Купить
                </button>
              </div>
            </form>
          </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}